export const TOOLS = [
  {
    id: "merge",
    name: "Gabungkan PDF",
    nameEn: "Merge PDF",
    desc: "Gabungkan beberapa PDF menjadi satu dokumen dalam urutan yang Anda inginkan.",
    descEn: "Combine PDFs in the order you want with the easiest PDF merger available.",
    icon: "Layers",
    color: "#E5322D",
    category: "organize",
    endpoint: "/api/merge",
    multipleFiles: true,
    accept: ".pdf"
  },
  {
    id: "split",
    name: "Pisahkan PDF",
    nameEn: "Split PDF",
    desc: "Pisahkan satu halaman atau seluruh rangkaian untuk konversi mudah ke berkas PDF independen.",
    descEn: "Separate one page or a whole set for easy conversion into independent PDF files.",
    icon: "Scissors",
    color: "#FF7B00",
    category: "organize",
    endpoint: "/api/split",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "compress",
    name: "Kompres PDF",
    nameEn: "Compress PDF",
    desc: "Kurangi ukuran berkas PDF Anda sambil mempertahankan kualitas terbaik.",
    descEn: "Reduce file size while optimizing for maximal PDF quality.",
    icon: "Minimize2",
    color: "#38B44A",
    category: "optimize",
    endpoint: "/api/compress",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "pdf-to-word",
    name: "PDF ke Word",
    nameEn: "PDF to Word",
    desc: "Konversi dokumen PDF Anda menjadi berkas DOCX yang dapat diedit dengan mudah.",
    descEn: "Convert your PDF to WORD documents with incredible accuracy.",
    icon: "FileText",
    color: "#2072B8",
    category: "convert",
    endpoint: "/api/pdf-to-word",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "word-to-pdf",
    name: "Word ke PDF",
    nameEn: "Word to PDF",
    desc: "Konversi berkas DOC & DOCX Microsoft Word menjadi dokumen PDF berkualitas tinggi.",
    descEn: "Make DOC and DOCX files easy to read by converting them to PDF.",
    icon: "FileCheck",
    color: "#1B5E20",
    category: "convert",
    endpoint: "/api/word-to-pdf",
    multipleFiles: false,
    accept: ".doc,.docx"
  },
  {
    id: "pdf-to-excel",
    name: "PDF ke Excel",
    nameEn: "PDF to Excel",
    desc: "Ekstrak data tabel dari berkas PDF langsung ke lembar kerja Excel XLSX.",
    descEn: "Pull data straight from PDFs into Excel spreadsheets in a few short seconds.",
    icon: "FileSpreadsheet",
    color: "#107C41",
    category: "convert",
    endpoint: "/api/pdf-to-excel",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "pdf-to-image",
    name: "PDF ke Gambar",
    nameEn: "PDF to JPG",
    desc: "Ekstrak semua gambar atau simpan setiap halaman PDF sebagai berkas JPG/PNG.",
    descEn: "Extract all images contained in a PDF or convert each page to JPG.",
    icon: "Image",
    color: "#7A288A",
    category: "convert",
    endpoint: "/api/pdf-to-image",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "image-to-pdf",
    name: "Gambar ke PDF",
    nameEn: "JPG to PDF",
    desc: "Ubah foto JPG dan PNG menjadi berkas PDF dalam hitungan detik.",
    descEn: "Convert JPG images to PDF in seconds. Easily adjust orientation and margins.",
    icon: "FileImage",
    color: "#C2185B",
    category: "convert",
    endpoint: "/api/image-to-pdf",
    multipleFiles: true,
    accept: "image/*"
  },
  {
    id: "rotate",
    name: "Putar PDF",
    nameEn: "Rotate PDF",
    desc: "Putar halaman PDF sesuai sudut yang Anda inginkan.",
    descEn: "Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!",
    icon: "RotateCw",
    color: "#F7A600",
    category: "organize",
    endpoint: "/api/rotate",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "watermark",
    name: "Cap Air (Watermark)",
    nameEn: "Watermark PDF",
    desc: "Tambahkan teks cap air di atas PDF Anda dengan transparansi yang sesuai.",
    descEn: "Stamp an image or text over your PDF in seconds. Choose position and opacity.",
    icon: "Stamp",
    color: "#E040FB",
    category: "edit",
    endpoint: "/api/watermark",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "page-numbers",
    name: "Nomor Halaman",
    nameEn: "Page Numbers",
    desc: "Tambahkan penomoran halaman otomatis pada berkas PDF Anda dengan posisi yang rapi.",
    descEn: "Add page numbers into PDF documents easily with customized positioning.",
    icon: "Hash",
    color: "#9C27B0",
    category: "edit",
    endpoint: "/api/page-numbers",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "protect",
    name: "Kunci PDF",
    nameEn: "Protect PDF",
    desc: "Enkripsi berkas PDF Anda dengan kata sandi untuk mencegah akses tidak sah.",
    descEn: "Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.",
    icon: "Lock",
    color: "#D32F2F",
    category: "security",
    endpoint: "/api/protect",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "unlock",
    name: "Buka Sandi PDF",
    nameEn: "Unlock PDF",
    desc: "Hapus proteksi kata sandi dari PDF Anda.",
    descEn: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
    icon: "Unlock",
    color: "#009688",
    category: "security",
    endpoint: "/api/unlock",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "ocr",
    name: "PDF OCR",
    nameEn: "OCR PDF",
    desc: "Pindai teks pada PDF hasil scan sehingga teks dapat disalin dan dicari.",
    descEn: "Convert scanned PDF to searchable and selectable document easily.",
    icon: "Eye",
    color: "#3F51B5",
    category: "edit",
    endpoint: "/api/ocr",
    multipleFiles: false,
    accept: ".pdf"
  },
  {
    id: "hd-image",
    name: "HD-kan Foto (Upscale)",
    nameEn: "Enhance Photo HD",
    desc: "Tingkatkan ketajaman, resolusi, dan kualitas gambar/foto Anda menjadi HD jernih secara instan.",
    descEn: "Upscale resolution, sharpen details, and enhance photo quality to HD instantly.",
    icon: "Sparkles",
    color: "#8B5CF6",
    category: "convert",
    endpoint: "/api/enhance-image",
    multipleFiles: false,
    accept: ".jpg,.jpeg,.png,.webp"
  }
];
